# Generated by Django 5.1.1 on 2026-07-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_bloodrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='available',
            new_name='availability',
        ),
    ]
